# Generated by Django 3.2.9 on 2021-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
